/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NgoIndexRouteImport } from './routes/ngo.index'
import { Route as DonorIndexRouteImport } from './routes/donor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DonorNewRouteImport } from './routes/donor.new'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoIndexRoute = NgoIndexRouteImport.update({
  id: '/ngo/',
  path: '/ngo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorIndexRoute = DonorIndexRouteImport.update({
  id: '/donor/',
  path: '/donor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorNewRoute = DonorNewRouteImport.update({
  id: '/donor/new',
  path: '/donor/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/donor/new': typeof DonorNewRoute
  '/admin/': typeof AdminIndexRoute
  '/donor/': typeof DonorIndexRoute
  '/ngo/': typeof NgoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/donor/new': typeof DonorNewRoute
  '/admin': typeof AdminIndexRoute
  '/donor': typeof DonorIndexRoute
  '/ngo': typeof NgoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/donor/new': typeof DonorNewRoute
  '/admin/': typeof AdminIndexRoute
  '/donor/': typeof DonorIndexRoute
  '/ngo/': typeof NgoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/donor/new'
    | '/admin/'
    | '/donor/'
    | '/ngo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/donor/new'
    | '/admin'
    | '/donor'
    | '/ngo'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onboarding'
    | '/donor/new'
    | '/admin/'
    | '/donor/'
    | '/ngo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  DonorNewRoute: typeof DonorNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DonorIndexRoute: typeof DonorIndexRoute
  NgoIndexRoute: typeof NgoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo/': {
      id: '/ngo/'
      path: '/ngo'
      fullPath: '/ngo/'
      preLoaderRoute: typeof NgoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/': {
      id: '/donor/'
      path: '/donor'
      fullPath: '/donor/'
      preLoaderRoute: typeof DonorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/new': {
      id: '/donor/new'
      path: '/donor/new'
      fullPath: '/donor/new'
      preLoaderRoute: typeof DonorNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  DonorNewRoute: DonorNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  DonorIndexRoute: DonorIndexRoute,
  NgoIndexRoute: NgoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
